// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: yrpcmsg.proto

/*
	Package yrpcmsg is a generated protocol buffer package.

	It is generated from these files:
		yrpcmsg.proto

	It has these top-level messages:
		Ymsg
		Yempty
		Ynocare
		UnixTime
		NatsOption
*/
package yrpcmsg

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import binary "encoding/binary"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// 系统中所有的消息交互底层都以此为包装
type Ymsg struct {
	// 整个rpc msg的长度，不包含此字段
	// 虽然这个长度可以很长，但是为了避免大包阻塞其它操作，通常都要限制长度,采用分包多发机制
	// 当使用基于包的传输通道时(udp/kcp/websocket)，此值可能为0(此时长度为收到的整个包的长度)
	Len uint32 `protobuf:"fixed32,1,opt,name=len,proto3" json:"len,omitempty"`
	// rpc command,rpc的命令和option
	// b15-b0(uint16):低16为rpc命令
	// b19-b16:body压缩方式 0:无压缩 1:lz4 2:zlib inflate/deflate
	// b23-b20:optbin压缩方式 0:无压缩 1:lz4 2:zlib inflate/deflate
	// b31-b24: not used
	Cmd uint32 `protobuf:"fixed32,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	// session id，登录后一定会有,用于后台区分不同的用户请求
	Sid []byte `protobuf:"bytes,3,opt,name=sid,proto3" json:"sid,omitempty"`
	// rpc call id,给分辨不同的rpc调用使用,调用方增1循环使用
	Cid uint32 `protobuf:"varint,4,opt,name=cid,proto3" json:"cid,omitempty"`
	// rpc no,从0开始增1使用,用于区分收到重复的包,特别是udp的情况下
	No uint32 `protobuf:"varint,5,opt,name=no,proto3" json:"no,omitempty"`
	// response code
	Res int32 `protobuf:"zigzag32,9,opt,name=res,proto3" json:"res,omitempty"`
	// msg body
	Body []byte `protobuf:"bytes,10,opt,name=body,proto3" json:"body,omitempty"`
	// optional str parameter,额外的信息,一般不会有,有些特殊命令里面可能用到
	Optstr string `protobuf:"bytes,11,opt,name=optstr,proto3" json:"optstr,omitempty"`
	// optional binary parameter,额外的信息,一般不会有,有些特殊命令里面可能用到
	Optbin []byte `protobuf:"bytes,12,opt,name=optbin,proto3" json:"optbin,omitempty"`
	// optional meta info,key=meta[i],value=meta[i+1]
	Meta []string `protobuf:"bytes,13,rep,name=meta" json:"meta,omitempty"`
}

func (m *Ymsg) Reset()                    { *m = Ymsg{} }
func (m *Ymsg) String() string            { return proto.CompactTextString(m) }
func (*Ymsg) ProtoMessage()               {}
func (*Ymsg) Descriptor() ([]byte, []int) { return fileDescriptorYrpcmsg, []int{0} }

func (m *Ymsg) GetLen() uint32 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *Ymsg) GetCmd() uint32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *Ymsg) GetSid() []byte {
	if m != nil {
		return m.Sid
	}
	return nil
}

func (m *Ymsg) GetCid() uint32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *Ymsg) GetNo() uint32 {
	if m != nil {
		return m.No
	}
	return 0
}

func (m *Ymsg) GetRes() int32 {
	if m != nil {
		return m.Res
	}
	return 0
}

func (m *Ymsg) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Ymsg) GetOptstr() string {
	if m != nil {
		return m.Optstr
	}
	return ""
}

func (m *Ymsg) GetOptbin() []byte {
	if m != nil {
		return m.Optbin
	}
	return nil
}

func (m *Ymsg) GetMeta() []string {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Yempty struct {
}

func (m *Yempty) Reset()                    { *m = Yempty{} }
func (m *Yempty) String() string            { return proto.CompactTextString(m) }
func (*Yempty) ProtoMessage()               {}
func (*Yempty) Descriptor() ([]byte, []int) { return fileDescriptorYrpcmsg, []int{1} }

// A generic nocare message that you can use to info the call is not important and no care the result.
// A typical example is to use it in report log/trace. For instance:
//
//     service Log {
//       rpc Log(infos) returns (yrpc.Ynocare);
//     }
//
type Ynocare struct {
}

func (m *Ynocare) Reset()                    { *m = Ynocare{} }
func (m *Ynocare) String() string            { return proto.CompactTextString(m) }
func (*Ynocare) ProtoMessage()               {}
func (*Ynocare) Descriptor() ([]byte, []int) { return fileDescriptorYrpcmsg, []int{2} }

type UnixTime struct {
	// Unix time, the number of miliseconds elapsed since January 1, 1970 UTC
	TimeUnix int64 `protobuf:"zigzag64,1,opt,name=time_unix,json=timeUnix,proto3" json:"time_unix,omitempty"`
	// utc time yyyy-MM-dd hh:mm:ss.zzz
	TimeStr string `protobuf:"bytes,2,opt,name=time_str,json=timeStr,proto3" json:"time_str,omitempty"`
}

func (m *UnixTime) Reset()                    { *m = UnixTime{} }
func (m *UnixTime) String() string            { return proto.CompactTextString(m) }
func (*UnixTime) ProtoMessage()               {}
func (*UnixTime) Descriptor() ([]byte, []int) { return fileDescriptorYrpcmsg, []int{3} }

func (m *UnixTime) GetTimeUnix() int64 {
	if m != nil {
		return m.TimeUnix
	}
	return 0
}

func (m *UnixTime) GetTimeStr() string {
	if m != nil {
		return m.TimeStr
	}
	return ""
}

type NatsOption struct {
	// original sid
	OrigSid []byte `protobuf:"bytes,1,opt,name=orig_sid,json=origSid,proto3" json:"orig_sid,omitempty"`
	// original cid
	OrigCid uint32 `protobuf:"varint,2,opt,name=orig_cid,json=origCid,proto3" json:"orig_cid,omitempty"`
	// nats replay
	Reply string `protobuf:"bytes,3,opt,name=reply,proto3" json:"reply,omitempty"`
	// optional binary parameters
	Obin []byte `protobuf:"bytes,4,opt,name=obin,proto3" json:"obin,omitempty"`
}

func (m *NatsOption) Reset()                    { *m = NatsOption{} }
func (m *NatsOption) String() string            { return proto.CompactTextString(m) }
func (*NatsOption) ProtoMessage()               {}
func (*NatsOption) Descriptor() ([]byte, []int) { return fileDescriptorYrpcmsg, []int{4} }

func (m *NatsOption) GetOrigSid() []byte {
	if m != nil {
		return m.OrigSid
	}
	return nil
}

func (m *NatsOption) GetOrigCid() uint32 {
	if m != nil {
		return m.OrigCid
	}
	return 0
}

func (m *NatsOption) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func (m *NatsOption) GetObin() []byte {
	if m != nil {
		return m.Obin
	}
	return nil
}

func init() {
	proto.RegisterType((*Ymsg)(nil), "yrpcmsg.Ymsg")
	proto.RegisterType((*Yempty)(nil), "yrpcmsg.Yempty")
	proto.RegisterType((*Ynocare)(nil), "yrpcmsg.Ynocare")
	proto.RegisterType((*UnixTime)(nil), "yrpcmsg.UnixTime")
	proto.RegisterType((*NatsOption)(nil), "yrpcmsg.NatsOption")
}
func (m *Ymsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ymsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Len != 0 {
		dAtA[i] = 0xd
		i++
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(m.Len))
		i += 4
	}
	if m.Cmd != 0 {
		dAtA[i] = 0x15
		i++
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(m.Cmd))
		i += 4
	}
	if len(m.Sid) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintYrpcmsg(dAtA, i, uint64(len(m.Sid)))
		i += copy(dAtA[i:], m.Sid)
	}
	if m.Cid != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintYrpcmsg(dAtA, i, uint64(m.Cid))
	}
	if m.No != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintYrpcmsg(dAtA, i, uint64(m.No))
	}
	if m.Res != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintYrpcmsg(dAtA, i, uint64((uint32(m.Res)<<1)^uint32((m.Res>>31))))
	}
	if len(m.Body) > 0 {
		dAtA[i] = 0x52
		i++
		i = encodeVarintYrpcmsg(dAtA, i, uint64(len(m.Body)))
		i += copy(dAtA[i:], m.Body)
	}
	if len(m.Optstr) > 0 {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintYrpcmsg(dAtA, i, uint64(len(m.Optstr)))
		i += copy(dAtA[i:], m.Optstr)
	}
	if len(m.Optbin) > 0 {
		dAtA[i] = 0x62
		i++
		i = encodeVarintYrpcmsg(dAtA, i, uint64(len(m.Optbin)))
		i += copy(dAtA[i:], m.Optbin)
	}
	if len(m.Meta) > 0 {
		for _, s := range m.Meta {
			dAtA[i] = 0x6a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *Yempty) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Yempty) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *Ynocare) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ynocare) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *UnixTime) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UnixTime) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TimeUnix != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintYrpcmsg(dAtA, i, uint64((uint64(m.TimeUnix)<<1)^uint64((m.TimeUnix>>63))))
	}
	if len(m.TimeStr) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintYrpcmsg(dAtA, i, uint64(len(m.TimeStr)))
		i += copy(dAtA[i:], m.TimeStr)
	}
	return i, nil
}

func (m *NatsOption) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NatsOption) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.OrigSid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintYrpcmsg(dAtA, i, uint64(len(m.OrigSid)))
		i += copy(dAtA[i:], m.OrigSid)
	}
	if m.OrigCid != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintYrpcmsg(dAtA, i, uint64(m.OrigCid))
	}
	if len(m.Reply) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintYrpcmsg(dAtA, i, uint64(len(m.Reply)))
		i += copy(dAtA[i:], m.Reply)
	}
	if len(m.Obin) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintYrpcmsg(dAtA, i, uint64(len(m.Obin)))
		i += copy(dAtA[i:], m.Obin)
	}
	return i, nil
}

func encodeVarintYrpcmsg(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Ymsg) Size() (n int) {
	var l int
	_ = l
	if m.Len != 0 {
		n += 5
	}
	if m.Cmd != 0 {
		n += 5
	}
	l = len(m.Sid)
	if l > 0 {
		n += 1 + l + sovYrpcmsg(uint64(l))
	}
	if m.Cid != 0 {
		n += 1 + sovYrpcmsg(uint64(m.Cid))
	}
	if m.No != 0 {
		n += 1 + sovYrpcmsg(uint64(m.No))
	}
	if m.Res != 0 {
		n += 1 + sozYrpcmsg(uint64(m.Res))
	}
	l = len(m.Body)
	if l > 0 {
		n += 1 + l + sovYrpcmsg(uint64(l))
	}
	l = len(m.Optstr)
	if l > 0 {
		n += 1 + l + sovYrpcmsg(uint64(l))
	}
	l = len(m.Optbin)
	if l > 0 {
		n += 1 + l + sovYrpcmsg(uint64(l))
	}
	if len(m.Meta) > 0 {
		for _, s := range m.Meta {
			l = len(s)
			n += 1 + l + sovYrpcmsg(uint64(l))
		}
	}
	return n
}

func (m *Yempty) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *Ynocare) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *UnixTime) Size() (n int) {
	var l int
	_ = l
	if m.TimeUnix != 0 {
		n += 1 + sozYrpcmsg(uint64(m.TimeUnix))
	}
	l = len(m.TimeStr)
	if l > 0 {
		n += 1 + l + sovYrpcmsg(uint64(l))
	}
	return n
}

func (m *NatsOption) Size() (n int) {
	var l int
	_ = l
	l = len(m.OrigSid)
	if l > 0 {
		n += 1 + l + sovYrpcmsg(uint64(l))
	}
	if m.OrigCid != 0 {
		n += 1 + sovYrpcmsg(uint64(m.OrigCid))
	}
	l = len(m.Reply)
	if l > 0 {
		n += 1 + l + sovYrpcmsg(uint64(l))
	}
	l = len(m.Obin)
	if l > 0 {
		n += 1 + l + sovYrpcmsg(uint64(l))
	}
	return n
}

func sovYrpcmsg(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozYrpcmsg(x uint64) (n int) {
	return sovYrpcmsg(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Ymsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowYrpcmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Ymsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Ymsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Len", wireType)
			}
			m.Len = 0
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			m.Len = uint32(binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cmd", wireType)
			}
			m.Cmd = 0
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			m.Cmd = uint32(binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sid", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpcmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthYrpcmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sid = append(m.Sid[:0], dAtA[iNdEx:postIndex]...)
			if m.Sid == nil {
				m.Sid = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cid", wireType)
			}
			m.Cid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpcmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cid |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field No", wireType)
			}
			m.No = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpcmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.No |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Res", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpcmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = int32((uint32(v) >> 1) ^ uint32(((v&1)<<31)>>31))
			m.Res = v
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Body", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpcmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthYrpcmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Body = append(m.Body[:0], dAtA[iNdEx:postIndex]...)
			if m.Body == nil {
				m.Body = []byte{}
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Optstr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpcmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthYrpcmsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Optstr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Optbin", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpcmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthYrpcmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Optbin = append(m.Optbin[:0], dAtA[iNdEx:postIndex]...)
			if m.Optbin == nil {
				m.Optbin = []byte{}
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Meta", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpcmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthYrpcmsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Meta = append(m.Meta, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipYrpcmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthYrpcmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Yempty) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowYrpcmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Yempty: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Yempty: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipYrpcmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthYrpcmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Ynocare) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowYrpcmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Ynocare: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Ynocare: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipYrpcmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthYrpcmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UnixTime) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowYrpcmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UnixTime: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UnixTime: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeUnix", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpcmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = (v >> 1) ^ uint64((int64(v&1)<<63)>>63)
			m.TimeUnix = int64(v)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeStr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpcmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthYrpcmsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimeStr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipYrpcmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthYrpcmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NatsOption) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowYrpcmsg
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NatsOption: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NatsOption: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrigSid", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpcmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthYrpcmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrigSid = append(m.OrigSid[:0], dAtA[iNdEx:postIndex]...)
			if m.OrigSid == nil {
				m.OrigSid = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrigCid", wireType)
			}
			m.OrigCid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpcmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OrigCid |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpcmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthYrpcmsg
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reply = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Obin", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpcmsg
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthYrpcmsg
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Obin = append(m.Obin[:0], dAtA[iNdEx:postIndex]...)
			if m.Obin == nil {
				m.Obin = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipYrpcmsg(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthYrpcmsg
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipYrpcmsg(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowYrpcmsg
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowYrpcmsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowYrpcmsg
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthYrpcmsg
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowYrpcmsg
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipYrpcmsg(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthYrpcmsg = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowYrpcmsg   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("yrpcmsg.proto", fileDescriptorYrpcmsg) }

var fileDescriptorYrpcmsg = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x91, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0x4d, 0xdb, 0xad, 0x6b, 0xdc, 0x44, 0x83, 0x48, 0x44, 0x28, 0xa5, 0x57, 0xbd, 0xda,
	0x40, 0xdf, 0x60, 0xde, 0x78, 0xa5, 0x90, 0xe9, 0xc5, 0xbc, 0x19, 0x6d, 0x13, 0x6a, 0x64, 0x49,
	0x4a, 0x9a, 0xc1, 0xfa, 0x16, 0x3e, 0xd6, 0x2e, 0x7d, 0x04, 0x99, 0x2f, 0x22, 0x27, 0x2b, 0xde,
	0x7d, 0xff, 0x9f, 0x9f, 0x70, 0xce, 0x7f, 0xf0, 0xac, 0xb7, 0x6d, 0xad, 0xba, 0x66, 0xde, 0x5a,
	0xe3, 0x0c, 0x89, 0x07, 0x99, 0x1f, 0x10, 0x8e, 0xd6, 0xaa, 0x6b, 0xc8, 0x25, 0x0e, 0xb7, 0x42,
	0x53, 0x94, 0xa1, 0x22, 0x66, 0x80, 0xe0, 0xd4, 0x8a, 0xd3, 0xe0, 0xe4, 0xd4, 0x8a, 0x83, 0xd3,
	0x49, 0x4e, 0xc3, 0x0c, 0x15, 0x53, 0x06, 0xe8, 0x33, 0x92, 0xd3, 0x28, 0x43, 0xc5, 0x8c, 0x01,
	0x92, 0x0b, 0x1c, 0x68, 0x43, 0x47, 0xde, 0x08, 0xb4, 0x81, 0x84, 0x15, 0x1d, 0x4d, 0x32, 0x54,
	0x5c, 0x31, 0x40, 0x42, 0x70, 0x54, 0x19, 0xde, 0x53, 0xec, 0xbf, 0xf1, 0x4c, 0x6e, 0xf0, 0xd8,
	0xb4, 0xae, 0x73, 0x96, 0x9e, 0x67, 0xa8, 0x48, 0xd8, 0xa0, 0x06, 0xbf, 0x92, 0x9a, 0x4e, 0x7d,
	0x7a, 0x50, 0xf0, 0x87, 0x12, 0xae, 0xa4, 0xb3, 0x2c, 0x2c, 0x12, 0xe6, 0x39, 0x9f, 0xe0, 0xf1,
	0x5a, 0xa8, 0xd6, 0xf5, 0x79, 0x82, 0xe3, 0xb5, 0x36, 0x75, 0x69, 0x45, 0xbe, 0xc4, 0x93, 0x37,
	0x2d, 0xf7, 0xaf, 0x52, 0x09, 0x72, 0x87, 0x13, 0x27, 0x95, 0xd8, 0xec, 0xb4, 0xdc, 0xfb, 0x45,
	0x09, 0x9b, 0x80, 0x01, 0x01, 0x72, 0x8b, 0x3d, 0x6f, 0x60, 0x86, 0xc0, 0xcf, 0x10, 0x83, 0x5e,
	0x39, 0x9b, 0x6f, 0x31, 0x7e, 0x2e, 0x5d, 0xf7, 0xd2, 0x3a, 0x69, 0x34, 0x04, 0x8d, 0x95, 0xcd,
	0x06, 0x9a, 0x40, 0x7e, 0xa8, 0x18, 0xf4, 0x4a, 0xf2, 0xff, 0x27, 0xa8, 0x24, 0xf0, 0x0d, 0xf8,
	0xa7, 0x47, 0xc9, 0xc9, 0x35, 0x1e, 0x59, 0xd1, 0x6e, 0x7b, 0x5f, 0x5e, 0xc2, 0x4e, 0x02, 0xd6,
	0x30, 0xb0, 0x5c, 0x74, 0xaa, 0x02, 0x78, 0x79, 0x7f, 0x38, 0xa6, 0xe8, 0xfb, 0x98, 0xa2, 0x9f,
	0x63, 0x8a, 0xbe, 0x7e, 0xd3, 0xb3, 0xa7, 0xf0, 0x3d, 0x6d, 0xa4, 0xfb, 0xd8, 0x55, 0xf3, 0xda,
	0xa8, 0x45, 0x5f, 0xea, 0xe6, 0x73, 0xa7, 0x6b, 0xc3, 0xc5, 0x62, 0xb8, 0x62, 0x35, 0xf6, 0x57,
	0x7d, 0xf8, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x80, 0x03, 0x1d, 0x09, 0xe6, 0x01, 0x00, 0x00,
}
